import test from 'node:test'; import assert from 'node:assert/strict';
import {timerSeconds,startTimer,stopTimer,addTimerSeconds} from '../src/timer.js';
import {calculateWorkload,setWorkload,workloadState} from '../src/heatmap.js';
import {selectExercise} from '../src/selection.js'; import {VERSION,dailyTotal,freshState,sanitizeState,complete,skip,streak} from '../src/state.js'; import {localDateKey,retainHistory} from '../src/date.js'; import {chartSeries} from '../src/stats.js';

test('timer passes below zero',()=>assert.equal(timerSeconds({seconds:1,running:true,startedAt:0},3000),-2));
test('timer pause, resume, and timestamp reload timing',()=>{let t=startTimer({seconds:10,running:false,startedAt:null},1000);t=stopTimer(t,4000);assert.equal(t.seconds,7);t=startTimer(t,9000);assert.equal(timerSeconds(t,11000),5);assert.deepEqual(JSON.parse(JSON.stringify(t)),t)});
test('adding reward settles elapsed time first',()=>assert.equal(timerSeconds(addTimerSeconds({seconds:10,running:true,startedAt:0},60,5000),5000),65));
const set=(selected,overrides={})=>({...selected,repetitions:8,weight:0,speed:'normal',...overrides});
const events=count=>Array.from({length:count},(_,i)=>({id:`event-${i}`,timestamp:`2026-01-0${i+1}T12:00:00.000Z`,date:`2026-01-0${i+1}`,group:'Legs',exercise:'squat',repetitions:8,weight:0,speed:'normal'}));

test('multiple completions of the same exercise remain distinct ordered events',()=>{const s=freshState(()=>0),first=complete(s,set(s.selected),new Date(2026,0,2,12),()=>0,()=> 'first'),done=complete(first,set(s.selected,{repetitions:12,weight:2.5,speed:'slow'}),new Date(2026,0,2,13),()=>0,()=> 'second');const day=done.history['2026-01-02'];assert.equal(dailyTotal(day),2);assert.deepEqual(day.events.map(x=>x.id),['first','second']);assert.deepEqual(day.events.map(x=>x.repetitions),[8,12])});
test('completion preserves all metadata, rewards, and creates the next offer',()=>{const s=freshState(()=>0),now=new Date(2026,0,2,12),done=complete(s,set(s.selected,{weight:'12.75',speed:'plyometric'}),now,()=>.9,()=> 'stable-id');assert.deepEqual(done.history['2026-01-02'].events[0],{id:'stable-id',timestamp:now.toISOString(),date:'2026-01-02',group:s.selected.group,exercise:s.selected.exercise,repetitions:8,weight:12.75,speed:'plyometric'});assert.equal(done.timer.seconds,1800);assert.notDeepEqual(done.selected,s.selected)});
test('daily target is saved on first completion and survives later configuration changes',()=>{let s=freshState(()=>0);s.config.dailyTarget=2;s=complete(s,set(s.selected),new Date(2026,0,2,12),()=>0,()=> 'one');s.config.dailyTarget=9;s=complete(s,set(s.selected),new Date(2026,0,2,13),()=>0,()=> 'two');assert.equal(s.history['2026-01-02'].target,2);assert.equal(streak(s.history,new Date(2026,0,2,14),9),1)});
test('completion accepts every speed and decimal or zero weights',()=>{for(const [speed,weight] of [['slow',0],['normal','0.0'],['plyometric','12.75']]){const s=freshState(()=>0),done=complete(s,set(s.selected,{speed,weight}),new Date(2026,0,2,12),()=>0,()=>speed);assert.equal(done.history['2026-01-02'].events[0].speed,speed);assert.equal(done.history['2026-01-02'].events[0].weight,Number(weight))}});
test('completion rejects invalid repetitions',()=>{const s=freshState(()=>0);for(const repetitions of [0,-1,1.5,''])assert.throws(()=>complete(s,set(s.selected,{repetitions})),/positive integer/)});
test('skip changes only the random offer and records no completion',()=>{const s=freshState(()=>0),skipped=skip(s,()=>.9);assert.notDeepEqual(skipped.selected,s.selected);assert.deepEqual(skipped.timer,s.timer);assert.deepEqual(skipped.history,s.history)});
test('weighted selection respects exact boundaries',()=>{const groups=[{name:'A',weight:2,exercises:['a']},{name:'B',weight:1,exercises:['b']}];let draws=[0,0];assert.equal(selectExercise(groups,()=>draws.shift()).group,'A');draws=[2/3,0];assert.equal(selectExercise(groups,()=>draws.shift()).group,'B')});
test('old-version cached state safely falls back',()=>{assert.equal(sanitizeState({version:VERSION-1,config:{dailyTarget:18}}).version,VERSION);assert.equal(sanitizeState(null).version,VERSION)});
test('version-2 configs without display mappings are migrated without losing saved state',()=>{const raw=freshState(()=>0),custom={name:'Mobility',weight:1,exercises:['stretch']};raw.config.groups=raw.config.groups.map(({display,...group})=>group).concat(custom);raw.timer={seconds:90,running:false,startedAt:null};raw.selected={group:'Mobility',exercise:'stretch'};raw.history={'2026-01-02':{target:3,events:[]}};const clean=sanitizeState(raw,()=>0,new Date(2026,0,2));assert.deepEqual(clean.config.groups[0].display,{type:'body',regions:['upper-legs']});assert.deepEqual(clean.config.groups.at(-1).display,{type:'non-body',regions:[]});assert.deepEqual(clean.timer,raw.timer);assert.deepEqual(clean.selected,raw.selected);assert.deepEqual(clean.history,raw.history)});
test('sanitization rejects malformed events, duplicate IDs, and unknown speeds',()=>{const raw=freshState(()=>0),valid={id:'valid',timestamp:'2026-01-02T12:00:00.000Z',date:'2026-01-02',group:'Legs',exercise:'squat',repetitions:8,weight:0,speed:'normal'};raw.history={'2026-01-02':{target:3,events:[valid,{...valid,id:'bad-speed',speed:'turbo'},{...valid,id:'bad-date',date:'2026-01-03'},{...valid}]}};const clean=sanitizeState(raw,()=>0,new Date(2026,0,2));assert.deepEqual(clean.history['2026-01-02'].events,[valid]);assert.equal(clean.history['2026-01-02'].target,3)});
test('local date keys put events on the correct side of a local midnight',()=>{let s=freshState(()=>0);s=complete(s,set(s.selected),new Date(2026,5,1,23,59),()=>0,()=> 'before');s=complete(s,set(s.selected),new Date(2026,5,2,0,0),()=>0,()=> 'after');assert.deepEqual(Object.keys(s.history),['2026-06-01','2026-06-02']);assert.equal(s.history['2026-06-01'].events[0].date,'2026-06-01');assert.equal(s.history['2026-06-02'].events[0].date,'2026-06-02')});
test('local date uses local calendar at rollover',()=>{assert.equal(localDateKey(new Date(2026,5,1,23,59)),'2026-06-01');assert.equal(localDateKey(new Date(2026,5,2,0,0)),'2026-06-02')});
test('history retention preserves event-based days for at least 366 local days',()=>{const h={'2024-12-31':{target:1,events:events(1)},'2025-01-01':{target:1,events:events(1)},'2026-01-01':{target:1,events:events(1)}};const kept=retainHistory(h,new Date(2026,0,1),366);assert.ok(!kept['2024-12-31']);assert.equal(kept['2025-01-01'],h['2025-01-01'])});
test('chart derives daily totals from event arrays and includes zero days',()=>{const s=chartSeries({'2026-01-10':{target:3,events:events(3)}},'week',new Date(2026,0,10));assert.equal(s.length,7);assert.equal(s[0].value,0);assert.equal(s.at(-1).value,3)});
test('streak ignores incomplete today and honors historical targets',()=>{const h={'2026-01-08':{target:2,events:events(2)},'2026-01-09':{target:3,events:events(3)},'2026-01-10':{target:3,events:events(1)}};assert.equal(streak(h,new Date(2026,0,10),18),2);h['2026-01-10'].events=events(3);assert.equal(streak(h,new Date(2026,0,10),18),3)});

const bodyGroup=(name,weight=1,regions=['chest'])=>({name,weight,display:{type:'body',regions},exercises:['x']});
const heatEvent=(group,repetitions=10,speed='normal',weight=0)=>({group,repetitions,speed,weight});
const heatDay=(...items)=>({events:items});
test('heatmap applies explicit recency decay over local calendar days',()=>{const groups=[bodyGroup('A')],history={'2026-01-10':heatDay(heatEvent('A')),'2026-01-09':heatDay(heatEvent('A')),'2026-01-08':heatDay(heatEvent('A')),'2026-01-07':heatDay(heatEvent('A'))};assert.equal(calculateWorkload(history,groups,new Date(2026,0,10,12)).groups.A.raw,23)});
test('heatmap ignores records aged four days and future-dated records',()=>{const groups=[bodyGroup('A')],history={'2026-01-06':heatDay(heatEvent('A',99)),'2026-01-11':heatDay(heatEvent('A',99))};assert.equal(calculateWorkload(history,groups,new Date(2026,0,10,12)).groups.A.raw,0)});
test('selection weight normalization prevents frequently offered groups dominating',()=>{const groups=[bodyGroup('A',2),bodyGroup('B',1)],history={'2026-01-10':heatDay(heatEvent('A',20),heatEvent('B',10))};const result=calculateWorkload(history,groups,new Date(2026,0,10));assert.equal(result.groups.A.raw,result.groups.B.raw)});
test('zero group weight uses a finite neutral divisor',()=>{const result=calculateWorkload({'2026-01-10':heatDay(heatEvent('A'))},[bodyGroup('A',0)],new Date(2026,0,10));assert.equal(result.groups.A.raw,10);assert.ok(Number.isFinite(result.groups.A.score))});
test('set workload applies speed modifiers and neutral bodyweight factor',()=>{assert.equal(setWorkload(heatEvent('A',10,'slow')),8);assert.equal(setWorkload(heatEvent('A',10,'normal')),10);assert.equal(setWorkload(heatEvent('A',10,'plyometric')),12.5);assert.equal(setWorkload(heatEvent('A',10,'normal',50)),15)});
test('relative thresholds classify fresh, moderate, and high groups',()=>{const groups=[bodyGroup('High'),bodyGroup('Mid'),bodyGroup('Low'),bodyGroup('Fresh')],history={'2026-01-10':heatDay(heatEvent('High',100),heatEvent('Mid',50),heatEvent('Low',20))};const result=calculateWorkload(history,groups,new Date(2026,0,10));assert.deepEqual(Object.fromEntries(Object.entries(result.groups).map(([name,value])=>[name,value.state])),{High:'red',Mid:'orange',Low:'green',Fresh:'green'});assert.equal(workloadState(2/3),'red');assert.equal(workloadState(1/3),'orange')});
test('multi-region group contribution is divided evenly',()=>{const result=calculateWorkload({'2026-01-10':heatDay(heatEvent('A'))},[bodyGroup('A',1,['chest','shoulders'])],new Date(2026,0,10));assert.equal(result.regions.chest.score,.5);assert.equal(result.regions.shoulders.score,.5)});
test('non-body groups are returned as named workload results, not regions',()=>{const group={...bodyGroup('Balance'),display:{type:'non-body',regions:[]}};const result=calculateWorkload({'2026-01-10':heatDay(heatEvent('Balance'))},[group],new Date(2026,0,10));assert.equal(result.nonBody[0].name,'Balance');assert.equal(result.nonBody[0].state,'red');assert.deepEqual(result.regions,{})});
