import './style.css';
import { loadState,saveState,complete,skip,streak,STORAGE_KEY,freshState } from './state.js';
import { timerSeconds,startTimer,stopTimer,resetTimer,formatTimer } from './timer.js';
import { localDateKey } from './date.js'; import { chartSeries } from './stats.js'; import { drawChart } from './chart.js';
let state=loadState(),range='week'; const app=document.querySelector('#app');
function persist(){saveState(state)}
function render(){const today=state.history[localDateKey()]?.total||0,s=streak(state.history,new Date(),state.config.dailyTarget);app.innerHTML=`
 <header><div><span class="eyebrow">DAILY DISCIPLINE</span><h1>Wesley’s House <em>of Pain.</em></h1></div><button class="icon" id="settings" aria-label="Open settings">⚙</button></header>
 <main><section class="hero panel"><div class="timer" id="timer" aria-live="polite">${formatTimer(timerSeconds(state.timer))}</div><div class="timer-controls"><button id="start">${state.timer.running?'Pause':'Start'}</button><button class="ghost" id="reset">Reset</button></div><div class="exercise"><span class="eyebrow">YOUR NEXT SET · ${state.selected?.group||'No group'}</span><h2>${state.selected?.exercise||'Add an exercise in settings'}</h2></div><div class="actions"><button class="complete" id="complete" ${state.selected?'':'disabled'}>✓ Complete <small>+${state.config.rewardMinutes} min</small></button><button class="ghost" id="skip" ${state.selected?'':'disabled'}>Skip →</button></div></section>
 <aside class="stats"><article class="panel stat"><span>Today</span><strong>${today}<small> / ${state.config.dailyTarget}</small></strong><div class="progress"><i style="width:${Math.min(100,today/state.config.dailyTarget*100)}%"></i></div></article><article class="panel stat"><span>Current streak</span><strong>${s}<small> ${s===1?'day':'days'}</small></strong><p>Incomplete today won’t break yesterday’s streak.</p></article></aside>
 <section class="panel history"><div class="section-head"><div><span class="eyebrow">CONSISTENCY</span><h2>Completed exercises</h2></div><div class="tabs" role="group" aria-label="Chart range">${['week','month','year'].map(x=>`<button data-range="${x}" class="${range===x?'active':''}">${x}</button>`).join('')}</div></div><canvas id="chart" role="img" aria-label="Daily completed exercise chart"></canvas></section></main>
 <dialog id="dialog"><form id="config"><div class="section-head"><h2>Configuration</h2><button type="button" class="icon" id="close" aria-label="Close settings">×</button></div><div class="fields"><label>Daily target<input name="target" type="number" min="1" step="1" required value="${state.config.dailyTarget}"></label><label>Completion reward (minutes)<input name="reward" type="number" min="1" step="1" required value="${state.config.rewardMinutes}"></label></div><h3>Exercise groups</h3><p class="help">One exercise per line. Weights must be positive.</p><div class="groups">${state.config.groups.map((g,i)=>`<fieldset><label>Group name<input name="name-${i}" required value="${escapeHtml(g.name)}"></label><label>Weight<input name="weight-${i}" type="number" min="0.1" step="0.1" required value="${g.weight}"></label><label class="wide">Exercises<textarea name="exercises-${i}" required>${escapeHtml(g.exercises.join('\n'))}</textarea></label><button type="button" class="danger" data-remove="${i}">Remove group</button></fieldset>`).join('')}</div><div class="dialog-actions"><button type="button" class="ghost" id="add">+ Add group</button><button type="submit">Save configuration</button></div><button type="button" class="danger reset-data" id="reset-data">Reset all saved data</button></form></dialog>`;
 bind();drawChart(document.querySelector('#chart'),chartSeries(state.history,range));}
function escapeHtml(x){return x.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function bind(){document.querySelector('#start').onclick=()=>{state={...state,timer:state.timer.running?stopTimer(state.timer):startTimer(state.timer)};persist();render()};document.querySelector('#reset').onclick=()=>{state={...state,timer:resetTimer()};persist();render()};document.querySelector('#complete').onclick=()=>{state=complete(state);persist();render()};document.querySelector('#skip').onclick=()=>{state=skip(state);persist();render()};document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{range=b.dataset.range;render()});const dialog=document.querySelector('#dialog');document.querySelector('#settings').onclick=()=>dialog.showModal();document.querySelector('#close').onclick=()=>dialog.close();document.querySelector('#add').onclick=()=>{state.config.groups.push({name:'New group',weight:1,exercises:['new exercise']});render();document.querySelector('#dialog').showModal()};document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{if(confirm('Remove this group? You can cancel without saving by closing settings.')){state.config.groups.splice(+b.dataset.remove,1);render();document.querySelector('#dialog').showModal()}});document.querySelector('#config').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),groups=state.config.groups.map((_,i)=>({name:f.get(`name-${i}`).trim(),weight:+f.get(`weight-${i}`),exercises:f.get(`exercises-${i}`).split('\n').map(x=>x.trim()).filter(Boolean)}));if(!groups.length||groups.some(g=>!g.exercises.length)){alert('Keep at least one group and one exercise in every group.');return}state={...state,config:{dailyTarget:+f.get('target'),rewardMinutes:+f.get('reward'),groups}};persist();dialog.close();render()};document.querySelector('#reset-data').onclick=()=>{if(confirm('Reset timer, configuration, and all history? This cannot be undone.')){localStorage.removeItem(STORAGE_KEY);state=freshState();persist();render()}}}
setInterval(()=>{if(state.timer.running){document.querySelector('#timer').textContent=formatTimer(timerSeconds(state.timer));}},250);addEventListener('resize',()=>{const c=document.querySelector('#chart');if(c)drawChart(c,chartSeries(state.history,range))});render();
