import './style.css';
import bodyDiagram from './body.svg?raw';
import { BODY_REGIONS } from './defaults.js';
import { calculateWorkload } from './heatmap.js';
import { loadState,saveState,complete,skip,streak,STORAGE_KEY,freshState,SPEEDS,WEIGHT_UNITS,dailyTotal } from './state.js';
import { timerSeconds,startTimer,stopTimer,resetTimer,formatTimer,timerStatus } from './timer.js';
import { localDateKey } from './date.js'; import { chartSeries,exerciseHistory,setEntryDefaults } from './stats.js'; import { drawChart } from './chart.js';
import { backupFilename, restoreBackup, serializeBackup } from './backup.js';
import { applyConfigDraft, createConfigDraft } from './config.js';
let state=loadState(),range='week',configDraft=null,settingsOpen=false; const app=document.querySelector('#app');
function persist(){saveState(state)}
function render(){const displayedConfig=configDraft||state.config,todayEntry=state.history[localDateKey()],today=dailyTotal(todayEntry),s=streak(state.history,new Date(),state.config.dailyTarget),heatmap=calculateWorkload(state.history,state.config.groups),remaining=timerSeconds(state.timer),status=timerStatus(remaining),selectedHistory=exerciseHistory(state.history,state.selected?.exercise,state.selected?.group),entryDefaults=setEntryDefaults(state.history,state.selected);app.innerHTML=`
 <header><div><span class="eyebrow">DAILY DISCIPLINE</span><h1>Wesley’s House <em>of Pain.</em></h1></div><button class="icon" id="settings" aria-label="Open settings">⚙</button></header>
 <main><section class="hero panel"><div class="timer ${status}" id="timer" aria-live="polite"><span class="timer-value">${formatTimer(remaining)}</span><span class="sr-only timer-status">Timer status: ${status}</span></div><div class="timer-controls"><button id="start">${state.timer.running?'Pause':'Start'}</button><button class="ghost" id="reset">Reset</button></div><div class="exercise"><span class="eyebrow">YOUR NEXT SET · ${escapeHtml(state.selected?.group||'No group')}</span><h2>${escapeHtml(state.selected?.exercise||'Add an exercise in settings')}</h2></div><form id="set-entry"><div class="set-fields"><label>Exercise<select name="exercise" required><option value="random">${escapeHtml(state.selected?.exercise||'None available')}</option>${state.config.groups.map((g,groupIndex)=>`<optgroup label="${escapeHtml(g.name)}">${g.exercises.map((exercise,exerciseIndex)=>`<option value="configured:${groupIndex}:${exerciseIndex}">${escapeHtml(exercise)}</option>`).join('')}</optgroup>`).join('')}</select></label><label>Repetitions<input name="repetitions" type="number" min="1" step="1" required value="${entryDefaults.repetitions}"></label><label>Weight<input name="weight" type="number" min="0" step="any" required value="${entryDefaults.weight}"></label><label>Unit<select name="weightUnit" required>${WEIGHT_UNITS.map(unit=>`<option value="${unit}" ${unit===entryDefaults.weightUnit?'selected':''}>${unit}</option>`).join('')}</select></label><label>Speed<select name="speed" required>${SPEEDS.map(speed=>`<option value="${speed}" ${speed===entryDefaults.speed?'selected':''}>${speed}</option>`).join('')}</select></label><label class="set-note">Note <span>(optional)</span><textarea name="note" rows="2" placeholder="How did this set feel?"></textarea></label></div><div class="actions"><button class="complete" id="complete" ${state.selected?'':'disabled'}>✓ Complete <small>+${state.config.rewardMinutes} min</small></button><button type="button" class="ghost" id="skip" ${state.selected?'':'disabled'}>Skip →</button></div></form></section>
 <aside class="stats"><article class="panel stat"><span>Today</span><strong>${today}<small> / ${state.config.dailyTarget}</small></strong><div class="progress"><i style="width:${Math.min(100,today/state.config.dailyTarget*100)}%"></i></div></article><article class="panel stat"><span>Current streak</span><strong>${s}<small> ${s===1?'day':'days'}</small></strong><p>Incomplete today won’t break yesterday’s streak.</p></article><article class="panel exercise-history" aria-labelledby="exercise-history-heading"><div class="history-title"><span class="eyebrow">EXERCISE HISTORY</span><h2 id="exercise-history-heading">${escapeHtml(state.selected?.exercise||'No exercise selected')}</h2><span>${selectedHistory.length} ${selectedHistory.length===1?'set':'sets'} logged</span></div>${selectedHistory.length?`<ol>${selectedHistory.map(event=>`<li><time datetime="${event.timestamp}"><strong>${formatEventDate(event.timestamp)}</strong><span>${formatEventTime(event.timestamp)}</span></time>${event.note?`<p class="history-note">${escapeHtml(event.note)}</p>`:''}<dl><div><dt>Reps</dt><dd>${event.repetitions}</dd></div><div><dt>Weight</dt><dd>${event.weight} ${escapeHtml(event.weightUnit||'kg')}</dd></div><div><dt>Speed</dt><dd>${escapeHtml(event.speed)}</dd></div></dl></li>`).join('')}</ol>`:`<p class="history-empty">Complete this exercise to start building its history.</p>`}</article></aside>
 <section class="panel activity"><div class="section-head"><div><span class="eyebrow">TODAY’S ACTIVITY</span><h2>Completed today</h2></div></div>${todayEntry?.events.length?`<ol class="activity-list">${todayEntry.events.map(event=>`<li><div class="activity-name"><strong>${escapeHtml(event.exercise)}</strong><span>${escapeHtml(event.group)}</span></div><dl><div><dt>Reps</dt><dd>${event.repetitions}</dd></div><div><dt>Weight</dt><dd>${event.weight} ${escapeHtml(event.weightUnit||'kg')}</dd></div><div><dt>Speed</dt><dd>${escapeHtml(event.speed)}</dd></div><div><dt>Time</dt><dd><time datetime="${event.timestamp}">${formatEventTime(event.timestamp)}</time></dd></div></dl></li>`).join('')}</ol>`:`<p class="activity-empty" role="status">No exercises completed today yet.</p>`}</section>
 <section class="panel heatmap"><div class="section-head"><div><span class="eyebrow">4-DAY LOAD</span><h2>Recovery heatmap</h2></div><div class="heat-legend" aria-label="Workload legend"><span class="level-green">Fresh / low</span><span class="level-orange">Moderate</span><span class="level-red">High</span></div></div><div class="body-diagram">${bodyDiagram}</div><ul class="region-labels" aria-label="Body region workload">${BODY_REGIONS.map(region=>{const result=heatmap.regions[region.id]||{score:0,state:'green'};return `<li class="level-${result.state}"><span>${escapeHtml(region.label)}</span><strong>${Math.round(result.score*100)}%</strong></li>`}).join('')}</ul>${heatmap.nonBody.length?`<div class="non-body"><h3>Non-body work</h3>${heatmap.nonBody.map(group=>`<article class="level-${group.state}"><strong>${escapeHtml(group.name)}</strong><span>${Math.round(group.score*100)}% · ${group.state}</span></article>`).join('')}</div>`:''}</section>
 <section class="panel history"><div class="section-head"><div><span class="eyebrow">CONSISTENCY</span><h2>Completed exercises</h2></div><div class="tabs" role="group" aria-label="Chart range">${['week','month','year'].map(x=>`<button data-range="${x}" class="${range===x?'active':''}">${x}</button>`).join('')}</div></div><canvas id="chart" role="img" aria-label="Daily completed exercise chart"></canvas></section></main>
 <dialog id="dialog"><form id="config"><div class="section-head"><h2>Configuration</h2><button type="button" class="icon" id="close" aria-label="Close settings">×</button></div><div class="fields"><label>Daily target<input name="target" type="number" min="1" step="1" required value="${displayedConfig.dailyTarget}"></label><label>Completion reward (minutes)<input name="reward" type="number" min="1" step="1" required value="${displayedConfig.rewardMinutes}"></label></div><h3>Exercise groups</h3><p class="help">One exercise per line. Zero-weight groups are never randomly offered but remain valid for manually logged work.</p><div class="groups">${displayedConfig.groups.map((g,i)=>`<fieldset><label>Group name<input name="name-${i}" required value="${escapeHtml(g.name)}"></label><label>Weight<input name="weight-${i}" type="number" min="0" step="0.1" required value="${g.weight}"></label><label>Display classification<select name="display-${i}"><option value="body" ${g.display.type==='body'?'selected':''}>Body regions</option><option value="non-body" ${g.display.type==='non-body'?'selected':''}>Non-body</option></select></label><div class="region-options" aria-label="Regions for ${escapeHtml(g.name)}">${BODY_REGIONS.map(region=>`<label><input type="checkbox" name="region-${i}" value="${region.id}" ${g.display.regions?.includes(region.id)?'checked':''}>${region.label}</label>`).join('')}</div><label class="wide">Exercises<textarea name="exercises-${i}" required>${escapeHtml(g.exercises.join('\n'))}</textarea></label><button type="button" class="danger" data-remove="${i}">Remove group</button></fieldset>`).join('')}</div><div class="dialog-actions"><button type="button" class="ghost" id="add">+ Add group</button><button type="submit">Save configuration</button></div><section class="backup-controls" aria-labelledby="backup-heading"><h3 id="backup-heading">Backup and restore</h3><p class="help">Download all retained workout data, or replace current data from a compatible JSON backup.</p><div><button type="button" class="ghost" id="download-backup">Download backup</button><label class="restore-button" for="restore-backup">Restore backup</label><input class="sr-only" id="restore-backup" type="file" accept="application/json,.json"></div></section><button type="button" class="danger reset-data" id="reset-data">Reset all saved data</button></form></dialog>`;
 for(const element of document.querySelectorAll('[data-region]')){const result=heatmap.regions[element.dataset.region]||{state:'green'};element.classList.add(`level-${result.state}`)}
 bind();drawChart(document.querySelector('#chart'),chartSeries(state.history,range));if(settingsOpen&&!document.querySelector('#dialog').open)document.querySelector('#dialog').showModal();}
function escapeHtml(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function formatEventTime(timestamp){return new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(new Date(timestamp))}
function formatEventDate(timestamp){return new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(new Date(timestamp))}
function bind(){document.querySelector('#start').onclick=()=>{state={...state,timer:state.timer.running?stopTimer(state.timer):startTimer(state.timer)};persist();render()};document.querySelector('#reset').onclick=()=>{state={...state,timer:resetTimer()};persist();render()};document.querySelector('#set-entry').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),choice=f.get('exercise');let selected=state.selected;if(choice!=='random'){const [,groupIndex,exerciseIndex]=choice.split(':');const group=state.config.groups[+groupIndex];selected={group:group?.name,exercise:group?.exercises[+exerciseIndex]}}state=complete(state,{...selected,repetitions:f.get('repetitions'),weight:f.get('weight'),weightUnit:f.get('weightUnit'),speed:f.get('speed'),note:f.get('note')});persist();render()};document.querySelector('[name="exercise"]').onchange=e=>{if(e.target.value==='random')return;const [,groupIndex,exerciseIndex]=e.target.value.split(':'),group=state.config.groups[+groupIndex],exercise=group?.exercises[+exerciseIndex];if(!group||!exercise)return;state={...state,selected:{group:group.name,exercise}};persist();render()};document.querySelector('#skip').onclick=()=>{state=skip(state);persist();render()};document.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{range=b.dataset.range;render()});const dialog=document.querySelector('#dialog');
 const discardDraft=()=>{configDraft=null;settingsOpen=false};
 const readDraft=form=>{const f=new FormData(form),groups=configDraft.groups.map((_,i)=>{const type=f.get(`display-${i}`),regions=f.getAll(`region-${i}`);return {name:String(f.get(`name-${i}`)||'').trim(),weight:+f.get(`weight-${i}`),display:{type,regions:type==='body'?regions:[]},exercises:String(f.get(`exercises-${i}`)||'').split('\n').map(x=>x.trim()).filter(Boolean)}});return {dailyTarget:+f.get('target'),rewardMinutes:+f.get('reward'),groups}};
 const refreshDraft=mutate=>{configDraft=readDraft(document.querySelector('#config'));mutate();render()};
 document.querySelector('#settings').onclick=()=>{configDraft=createConfigDraft(state.config);settingsOpen=true;render()};
 document.querySelector('#close').onclick=()=>dialog.close();
 dialog.addEventListener('cancel',discardDraft);dialog.addEventListener('close',discardDraft);
 document.querySelector('#add').onclick=()=>refreshDraft(()=>configDraft.groups.push({name:'New group',weight:1,display:{type:'non-body',regions:[]},exercises:['new exercise']}));
 document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{if(confirm('Remove this group? You can cancel without saving by closing settings.'))refreshDraft(()=>configDraft.groups.splice(+b.dataset.remove,1))});
 document.querySelector('#config').onsubmit=e=>{e.preventDefault();configDraft=readDraft(e.target);try{state=applyConfigDraft(state,configDraft)}catch(error){alert(error.message);return}persist();settingsOpen=false;configDraft=null;dialog.close();render()};
 document.querySelector('#download-backup').onclick=()=>{const now=new Date(),blob=new Blob([serializeBackup(state,now)],{type:'application/json'}),link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=backupFilename(now);link.click();URL.revokeObjectURL(link.href)};document.querySelector('#restore-backup').onchange=async e=>{const input=e.target,file=input.files?.[0];if(!file)return;if(!confirm('Restore this backup? It will replace the current timer, configuration, selection, and workout history.')){input.value='';return}try{const text=await file.text(),restored=restoreBackup(text,state,localStorage,new Date());state=restored;dialog.close();render()}catch(error){input.value='';alert(`Backup could not be restored. ${error instanceof Error?error.message:'Please choose a valid backup file.'}`)}};document.querySelector('#reset-data').onclick=()=>{if(confirm('Reset timer, configuration, and all history? This cannot be undone.')){localStorage.removeItem(STORAGE_KEY);state=freshState();persist();render()}}}
setInterval(()=>{if(state.timer.running){const timer=document.querySelector('#timer'),remaining=timerSeconds(state.timer),status=timerStatus(remaining);timer.querySelector('.timer-value').textContent=formatTimer(remaining);timer.querySelector('.timer-status').textContent=`Timer status: ${status}`;timer.classList.remove('negative','warning','healthy');timer.classList.add(status);}},250);addEventListener('resize',()=>{const c=document.querySelector('#chart');if(c)drawChart(c,chartSeries(state.history,range))});render();

